### ISSUE TITLE
Maybe throw error with explanation if ts_gtrends is called without keywords?

### ISSUE THREAD

**Issue by uwethuemmel** [trendecon/trendecon#1]
Currently

> out <- ts_gtrends()

produces
    
    Downloading data for today+5-y
    Error in interest_over_time(widget, comparison_item, tz) (gtrends_with_backoff.R#70): Status 
    code was not 200. Returned status code:400
    Show stack trace

Google Trends is actually queried here. Maybe we should throw an error, instead.

https://github.com/trendecon/trendecon/blob/57b88b3d7847e40c467bc1e1fe746f9f7b09f08c/R/ts_gtrends.R#L18

**Comment by christophsax** [comment]
A micro think, @karoliskoncevicius, if you have time at some point.

**Comment by karoliskoncevicius** [comment]
Closed by the following pull request: https://github.com/trendecon/trendecon/pull/59
