### ISSUE TITLE
CRAN checks

### ISSUE THREAD

**Issue by christophsax** [trendecon/trendecon#10]
The remaining ones are all linked to documentation. @uwethuemmel, so perhaps something for you? 

```
W  checking Rd cross-references ...
   Missing link or links in documentation object 'proc_keyword_init.Rd':
     ‘[trendecon:aggregate_windows]{trendecon::aggregate_windows}’
   
   See section 'Cross-references' in the 'Writing R Extensions' manual.
   
W  checking for missing documentation entries (522ms)
   Undocumented code objects:
     ‘path_data’ ‘path_data_raw’ ‘path_keyword’ ‘path_trendecon’
     ‘proc_all’ ‘proc_keyword’ ‘read_keywords’ ‘write_keyword’
   All user-level objects in a package should have documentation entries.
   See chapter ‘Writing R documentation files’ in the ‘Writing R
   Extensions’ manual.
✔  checking for code/documentation mismatches (1.5s)
W  checking Rd \usage sections ...
   Undocumented arguments in documentation object 'proc_combine_freq'
     ‘keyword’
   
   Functions with \usage entries need to have the appropriate \alias
   entries, and all their arguments documented.
   The \usage entries must correspond to syntactically valid R code.
   See chapter ‘Writing R documentation files’ in the ‘Writing R
   Extensions’ manual.

```

**Comment by uwethuemmel** [comment]
@christophsax 
Yes, I can look into that. I suppose I have to run`devtools::check()`?

When doing that currently, I get the following error from the vignette:

> Error in (function (command = NULL, args = character(), error_on_status = TRUE, : System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
> E> Quitting from lines 27-35 (intro.Rmd) 
> E> Error: processing vignette 'intro.Rmd' failed with diagnostics:
> E> could not find function "keyword_plot"
> E> --- failed re-building 'intro.Rmd'
> E> 
> E> SUMMARY: processing the following file failed:
> E>   'intro.Rmd'
> E> 
> E> Error: Vignette re-building failed.
> E> Execution halted

**Comment by christophsax** [comment]
Do you have the latest stuff on master? I don't see a call to `keyword_plot` in `intro.Rmd`

**Comment by uwethuemmel** [comment]
You were right, I didn't have the latest version. What command did you run to produce the output above? When I run `devtools::check_man()`, my output has much less detail:

> Checking documentation...
> Undocumented arguments in documentation object 'proc_combine_freq'
>   ‘keyword’
> 
> Undocumented code objects:
>   ‘path_data’ ‘path_data_raw’ ‘path_keyword’ ‘path_trendecon’ ‘proc_all’ ‘read_keywords’ ‘write_keyword’

**Comment by christophsax** [comment]
devtools::check() should be good

**Comment by christophsax** [comment]
i guess devtools::check_man() only checks the problems related to doc

**Comment by christophsax** [comment]
Only a very few left:

```
❯ checking Rd cross-references ... WARNING
  Missing link or links in documentation object 'proc_aggregate_raw.Rd':
    ‘[trendecon:aggregate_windows]{trendecon::aggregate_windows()}’
  
  Missing link or links in documentation object 'proc_keyword_init.Rd':
    ‘[trendecon:aggregate_windows]{trendecon::aggregate_windows}’
  
  See section 'Cross-references' in the 'Writing R Extensions' manual.

❯ checking for missing documentation entries ... WARNING
  Undocumented code objects:
    ‘proc_all’
  All user-level objects in a package should have documentation entries.
  See chapter ‘Writing R documentation files’ in the ‘Writing R
  Extensions’ manual.

❯ checking Rd \usage sections ... WARNING
  Undocumented arguments in documentation object 'proc_aggregate_raw'
    ‘keyword’
  
  Functions with \usage entries need to have the appropriate \alias
  entries, and all their arguments documented.
  The \usage entries must correspond to syntactically valid R code.
  See chapter ‘Writing R documentation files’ in the ‘Writing R
  Extensions’ manual.
```
