### ISSUE TITLE
Question regarding the ts_gtrends_index

### ISSUE THREAD

**Issue by xvanbinsbergen** [trendecon/trendecon#108]
Dear contributors,

I am working on a research project in which I want to investigate the investor attention of the Israel-Palestine war. Now I would like to combine the various Google Trend keywords into ONE index; "Israeli-Palestinian War", "Israel Palestine Conflict", "US Support for Israel", "Support for Israel", "EU Support Israel". I tried this with the following feature: 

gtdata_average <- ts_gtrends_index(keyword = c("Israeli-Palestinian War", "Israel Palestine Conflict", "US Support for Israel", "Support for Israel", "EU Support Israel"), time = "2023-09-01 2024-02-29", sadj = TRUE)

However, R now takes a very long time each time to get the data and needs multiple attempts each time. In the end, I get the following error every time: 

_Errors:
- Seasonal period too large. See Section 2.7 of the Reference Manual on program limits
- Expected argument name or "}" but found ".1428571428614"
- Time series could not be read due to previously found errors
- Expected specification name but found "}"
- Specify series before user-defined adjustments
- Need to specify a series to identify _outliers_

Notes:
- Correct input errors in the order they are detected since the first one or two may be responsible for
  the others (especially if there are errors in the SERIES or COMPOSITE spec)._

Do you guys have any idea what I can do about this or what other function I can use to make ONE index out of the five different keywords? Thanks in advance!

**Comment by karoliskoncevicius** [comment]
Dear @xvanbinsbergen 

Please forgive for the late reply.

In essence, you are using the wrong function - `ts_gtrends_index()`. For creating an index you should be following the steps in the manual, here: https://trendecon.github.io/trendecon/articles/daily-series.html

In short, you would first have to call `proc_keyword_init()` for all the keywords you want to include in the index. This would download the files to your local computer drive.

    # geo = "" assumes you are looking for queries from all over the world
    proc_keyword_init("keyword1", geo = "")
    proc_keyword_init("keyword2", geo = "")
    proc_keyword_init("keyword3", geo = "")
    ...

And then combine them using `prox_index()`.

    proc_index(c("keyword1", "keyword2", "keyword3"), geo = "", "index_name")
    
Please note that this will download the data starting from 2014. At the moment building an index starting from a later day is not implemented.

Hope this helps!
