### ISSUE TITLE
Introductory Vignette

### ISSUE THREAD

**Issue by ninamuehlebach** [trendecon/trendecon#11]
I just pushed a first version of the Introductory Vignette.

I was not able to knit the markdown because i don't know how I get `library(trendecon)` to work. Therefore I don't know if it compiles. I was not sure for instance about how to refer to  functions in the text. 

What is still missing? should I extend more?

**Comment by christophsax** [comment]
Thanks! Looks good.
@ronaldindergand helps with review and will get back to you.
