### ISSUE TITLE
Obsolete comparison of averages in proc_aggregate_raw

### ISSUE THREAD

**Issue by uwethuemmel** [trendecon/trendecon#19]
I commented out code which was not anymore needed. Will have to decide if can be deleted.

https://github.com/trendecon/trendecon/blob/9374cfd60a306afab3a863ba40b284f475f22451/R/proc_aggregate_raw.R#L14-L18

**Comment by christophsax** [comment]
I added a better comment. It is probably good to keep it there, in case we want to investigate what it does.
