### ISSUE TITLE
Default path in proc_all.R wrong

### ISSUE THREAD

**Issue by uwethuemmel** [trendecon/trendecon#23]
Defaults to `.` not to `..`.

``` r
pkgload::load_all('~/Dropbox/trendecon/trendecon')
#> Loading trendecon
proc_all()
#> Error in proc_all(): 'data' and 'data-raw' not found in: /private/var/folders/4y/trn91xc52cqbpw8wzm_p7qgc0000gn/T/RtmpcJhwZw/reprex1489938bfa978. Make sure the two repositories are in the same folder
```

<sup>Created on 2020-05-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

https://github.com/trendecon/trendecon/blob/f7e51b27470cd24b5cb23884b9a7d3900c04a243/R/proc_all.R#L2

**Comment by uwethuemmel** [comment]
Actually, I did not change this because I did not want to break the current processing of downloads. 

@angelicambg how is the current folder structure for the data? Are the data directories 

- inside the trendecon directory (at the same level, as e.g. the folders `R` and `man`) 

or are the data directories 

- in the parent directory of trendecon?

**Comment by christophsax** [comment]
We should now call `proc_trendecon_ch(".")` in the `data` directory. The data repo is now independent of the location of the others.

**Comment by christophsax** [comment]
I think this good otherwise and could be closed.
