### ISSUE TITLE
Decide how to store data for different locations

### ISSUE THREAD

**Issue by uwethuemmel** [trendecon/trendecon#25]
Once we have solved #8 and we can download and process data for different locations, we need to decide how this data should be stored.

**Comment by uwethuemmel** [comment]
Possible options would be
- have a parent folders per country which then contain `data-raw` and `data`
- use suffixes or prefixes per country for `data-raw` and `data`
- move to a database altogether

**Comment by christophsax** [comment]
Data updates are fully automated and live now in `https://github.com/trendecon/data`. Once #29 is done, we could start using a better structure for more countries. Perhaps a single `data` folder, with a subfolder for each country, which conatins:

```
data/ch/gardening_d.csv
data/ch/gardening_w.csv
data/ch/gardening_m.csv
```
So this would have the same structure as the `indicator` folder, which we still need. This could also be sorted by country:

```
indicator/ch/Bauhaus_d.csv
indicator/ch/Bauhaus_w.csv
indicator/ch/Bauhaus_m.csv
```
Of course, the country code could also enter the name. But having everything by country would require a little less changes.

**Comment by christophsax** [comment]
In principle, this should work for Germany now as well.
