### ISSUE TITLE
Decide how to store/handle keywords for other countries

### ISSUE THREAD

**Issue by uwethuemmel** [trendecon/trendecon#26]
Currently, we have the keywords hardcoded. We need to decide how to deal with this when including other countries.

One option would be to have the keywords in a csv file, where each column corresponds to an index, and the keywords are then included in the columns. In this way, we could easily have different such csv files for different countries.

**Comment by christophsax** [comment]
Or how if [proc_trendecon_ch()](https://github.com/trendecon/trendecon/blob/master/R/proc_trendecon_ch.R) would call a function for each keyword? To have a function for each country (or every new project idea) would give us some extra flexibility.
