### ISSUE TITLE
in proc_keyword_init, can keyword take a vector?

### ISSUE THREAD

**Issue by christophsax** [trendecon/trendecon#30]

**Comment by christophsax** [comment]
@uwethuemmel I think it should not. It takes a long time to run, and needs some supervision.

**Comment by uwethuemmel** [comment]
@christophsax As far as I see, it only takes a single keyword:

https://github.com/trendecon/trendecon/blob/c0522d9d22e102bf21c9651861aaa2a0355b1f4c/R/proc_keyword_init.R#L32

**Comment by christophsax** [comment]
Which is good!
