### ISSUE TITLE
proc_keyword_latest fails without informative error if proc_keyword_init has not been called

### ISSUE THREAD

**Issue by uwethuemmel** [trendecon/trendecon#34]
This is not an issue if `proc_keyword_latest` is called by `proc_keyword`, since `proc_keyword` checks for the presence of initial keyword files and gives an informative error if such files are missing.

However, if `proc_keyword_latest` is called by itself, it fails without informative error. We can decide whether we want it to throw a similar error as `proc_keyword`. The same issue likely applies to all proc_ functions which are being called by proc_keyword.

**Comment by KKPMW** [comment]
Opinion: `proc_keyword_latest` in the code is only called from within `proc_keyword`. It is not an exported function so no user should run it and expect to get back an informative error in the case of failure.

I think as long as exported functions behave nicely - all is good.
