### ISSUE TITLE
rewrite proc_trendecon_ch() to not source the scripts.

### ISSUE THREAD

**Issue by christophsax** [trendecon/trendecon#36]
`proc_trendecon_de()` can be used as a boilerplate.

If done, adjust second vignette on `proc_` functions

**Comment by uwethuemmel** [comment]
@christophsax Some of the scripts call `ts_dygraphs`, for example:

https://github.com/trendecon/trendecon/blob/a88ee16d2ac788ba637e53339f0c4909a48c1eb0/inst/script/garden.R#L33

Do you want to keep that?

**Comment by christophsax** [comment]
> ts_dygraphs(x_prcomp) 

No, I don't.

So I thing we are done with this?
