### ISSUE TITLE
Vignette on `proc_` functions

### ISSUE THREAD

**Issue by christophsax** [trendecon/trendecon#4]
The skeleton for the second vignette:

https://github.com/trendecon/trendecon/blob/master/vignettes/daily-series.Rmd

The roxygen headers of the proc functions may be related to this.

**Comment by christophsax** [comment]
This one still needs a bit of work.

**Comment by christophsax** [comment]
@angelicambg Do you have some time to work on this soon?

**Comment by christophsax** [comment]
One of the many great features of our CI workflow is that the pkgdown site builds automatically:

https://trendecon.github.io/trendecon/articles/daily-series.html

**Comment by angelicambg** [comment]
Sorry I didn't have so much time during the week. But this weekend I'll work on this

**Comment by christophsax** [comment]
No problem @angelicambg. @uwethuemmel  drafted and I think it is almost good already. Perhaps we can start to work on the DE and AT series, and improve the vignette as we move along?
