### ISSUE TITLE
main indicator inverted?

### ISSUE THREAD

**Issue by christophsax** [trendecon/trendecon#41]
<img width="899" alt="image" src="https://user-images.githubusercontent.com/1390827/85185402-1676a680-b294-11ea-81dd-565bea4aed93.png">

The was no intention in this, right? Our main indicator is inverted now. 

@angelicambg @uwethuemmel

**Comment by angelicambg** [comment]
no, something happened. I just checked and it changed with the commit in data repo on June 17th. The commit on June 15th was still fine. But since the commits on June 15th and 17th to the trendecon repo are related with [tic.yml](https://github.com/trendecon/trendecon/commit/c9c8f30d863b4cf6c395f36c7902b664825a7cac) and documentation. I'm not sure what happened.

**Comment by uwethuemmel** [comment]
I think I know why this happens. The indicator now shows positive search frequencies like we have for all the other indicators, whereas previously we had the values inverted:

https://github.com/trendecon/trendecon/blob/946bc93bad3d1f25a4c00166d2c1addd12dd47cf/inst/script/trendecon.R#L16

I've missed that when moving to the new way of processing the indicators. Sorry. Will think about how to best deal with it.

**Comment by uwethuemmel** [comment]
@christophsax @angelicambg I made a quick fix in pull request #42

**Comment by uwethuemmel** [comment]
@christophsax @angelicambg 
So far, the main indicator still appears inverted on the website. Does that mean that the update to the code did not work, or has the website not yet been updated with the latest indicators?

**Comment by christophsax** [comment]
The latest update deleted everything. Mmmm.

<img width="751" alt="image" src="https://user-images.githubusercontent.com/1390827/85230491-d7aa3300-b3f0-11ea-8565-3cee604ba520.png">

**Comment by christophsax** [comment]
I will have a look

**Comment by christophsax** [comment]
I think the `ifelse` is the culprit, but it is quite hard to see what it does. It just uses the first value everywhere. Which then causes `ts_scale()` to go nuts, because there is no variation. `if_else()` would have given an error, so another reason to prefer it.


```
> filter(ts_prcomp(data), id == "PC1") 
# A tibble: 5,283 x 3
   id    time         value
   <chr> <date>       <dbl>
 1 PC1   2006-01-01  0.429 
 2 PC1   2006-01-02 -0.891 
 3 PC1   2006-01-03 -2.22  
 4 PC1   2006-01-04 -1.92  
 5 PC1   2006-01-05 -1.63  
 6 PC1   2006-01-06  0.0201
 7 PC1   2006-01-07  2.48  
 8 PC1   2006-01-08  1.51  
 9 PC1   2006-01-09 -0.128 
10 PC1   2006-01-10  1.13  
# … with 5,273 more rows
> 
> filter(ts_prcomp(data), id == "PC1") %>%
+     mutate(value = ifelse(index_name=="trendecon", -value, value))
# A tibble: 5,283 x 3
   id    time        value
   <chr> <date>      <dbl>
 1 PC1   2006-01-01 -0.429
 2 PC1   2006-01-02 -0.429
 3 PC1   2006-01-03 -0.429
 4 PC1   2006-01-04 -0.429
 5 PC1   2006-01-05 -0.429
 6 PC1   2006-01-06 -0.429
 7 PC1   2006-01-07 -0.429
 8 PC1   2006-01-08 -0.429
 9 PC1   2006-01-09 -0.429
10 PC1   2006-01-10 -0.429
# … with 5,273 more rows
```

**Comment by christophsax** [comment]
pushed a fix, let's hope it works tomorrow.

**Comment by christophsax** [comment]
This is what was behind:

``` r

library(tidyverse)

value <- c(1, 2)

# evaluates first element only (because the first arg is of length 1)
ifelse(TRUE, -value, value)
#> [1] -1

# gives an error
if_else(TRUE, -value, value)
#> Error: `true` must be length 1 (length of `condition`), not 2.

# in the `mutate()`, the single value is recycled over the whole length"
tibble(value = value) %>% 
  mutate(ans = -1)
#> # A tibble: 2 x 2
#>   value   ans
#>   <dbl> <dbl>
#> 1     1    -1
#> 2     2    -1
```

<sup>Created on 2020-06-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by uwethuemmel** [comment]
I see. Thanks for looking into it.

**Comment by christophsax** [comment]
seem all good again.

**Comment by angelicambg** [comment]
Our main indicator for CH is inverted now. @KKPMW and @christophsax the main indicator for all countries will be inverted as well?

**Comment by christophsax** [comment]
This was not intentional. Can you or @KKPMW revert the website?

@KKPMW any idea what caused it.

**Comment by christophsax** [comment]
It looks like Austria here:

https://github.com/trendecon/data/blob/master/README.md

**Comment by KKPMW** [comment]
@christophsax I have no idea what caused it.

My first guess is that this is a stochastic thing because of PC sign uncertainty. But in that case you should have seen some inversions in the past.

Does `ts_prcom()` has some mechanism or rule to choose one sign over the other? If yes, then it's probably something else.

**Comment by christophsax** [comment]
This looks not like inverted, but like Austria. If signs were inverted, it would go up until 5, not 12.

**Comment by KKPMW** [comment]
You are correct, I think it's data issue. Seems like the ch/trendecon.csv was replaced with at/trendecon.csv for some reason. Wonder if something is missing in GitHub actions.

Trying to replace the file manually.

**Comment by KKPMW** [comment]
OK I think I found the issue. Was my mistake.

Here is a fix: https://github.com/trendecon/trendecon/commit/115ce9087b65724d737e2f38d47a12c3574d8902

I change the location only in `path_keyword()` without realising it is in two places.

**Comment by KKPMW** [comment]
Can we somehow trigger refresh for the website to see if this fixes things?

**Comment by KKPMW** [comment]
If no I can do it manually

**Comment by KKPMW** [comment]
What was happening is this:

1. The files for CH were updated and stored in data/ch
2. The trendcon.csv file for DE was updated and stored in data/ch again (overwriting trendcon for CH)
3. The trendonc.csv file for AT was updated and also stored in data/ch (and we ended up with AT being in place of CH).

**Comment by KKPMW** [comment]
OK I think I managed to rerun the GitHub action jobs. If I am right this should fix the issue.

**Comment by angelicambg** [comment]
Thanks!! now it's back. I'll push changes for the website
