### ISSUE TITLE
Polish and use first vignette

### ISSUE THREAD

**Issue by christophsax** [trendecon/trendecon#44]
@KKPMW as discussed, can you polish the vignette at https://github.com/trendecon/trendecon/blob/master/vignettes/intro.Rmd? 

@ninamuehlebach has already worked on it and can be contacted in case of questions.

@uwethuemmel has worked on the package as well an can be contacted in case of questions as well.

@a1exgo is new on the project and would be glad to use and review the vignette. Perhaps you @KKPMW can let him know when you are done.

Thanks to all!

**Comment by KKPMW** [comment]
Will look into it now, have to get familiar with the package first. If there are any guidelines or suggestions from anyone, feel free to share them here. Otherwise I will try to make a judgement myself.

**Comment by KKPMW** [comment]
Hello @a1exgo , nice getting in touch.

I modified the first vignette, it can be found in this pull request: https://github.com/trendecon/trendecon/pull/45

Talked with @christophsax and he said the plan is for you to read through it and see if it makes sense and is easy to understand. Any comments questions or criticisms are welcome!

**Comment by KKPMW** [comment]
@christophsax I also added myself as maintainer.

Apparently having several maintainers is fine with R CMD check, so I left both you and me. Seems to only be CRAN policy. There are packages on BioConductor with multiple maintainers, i.e. : https://bioconductor.org/packages/release/bioc/html/a4.html

**Comment by KKPMW** [comment]
hmmm OK, maybe not (in that package they are written under one field actually). Removed your maintainer status in this case.

**Comment by a1exgo** [comment]
Hi @KKPMW, thank you, likewise!

I will have a look at it and comment directly in the pull request tomorrow morning.
