### ISSUE TITLE
'proc_index_clothing.R' - safe to delete?

### ISSUE THREAD

**Issue by KKPMW** [trendecon/trendecon#50]
I noticed there is a separate function in the package `proc_index_clothing()` that builds the index for clothing keywords.

@christophsax I assume it is deprecated now? Didn't find any place where it is called. Can it be deleted?

**Comment by christophsax** [comment]
Probably.

**Comment by KKPMW** [comment]
Deleted by clean up: https://github.com/trendecon/trendecon/pull/54
