### ISSUE TITLE
PC sign issue when aggregating multiple keywords

### ISSUE THREAD

**Issue by KKPMW** [trendecon/trendecon#55]
I suspect we have a PCA sign issue that potentially can invert any index.

Here is a short demonstration comparing CH and AT trendecon index raw data and PC1 aggregate:

First - prepare the data lists:

    library(tsbox)

    files <- c("Insolvenz_sa.csv", "Kurzarbeit_sa.csv", "Wirtschaftskrise_sa.csv", "arbeitslos_sa.csv")
    files_at <- file.path("https://raw.githubusercontent.com/trendecon/data/master/raw/at/", files)
    files_ch <- file.path("https://raw.githubusercontent.com/trendecon/data/master/raw/ch/", files)

    dats_at <- Map(read.csv, files_at)
    dats_at <- Map(ts_pick, dats_at, "seas_adj")
    dats_at <- Map(function(d, n) {d$id <- n; d}, dats_at, basename(names(dats_at)))

    dats_ch <- Map(read.csv, files_ch)
    dats_ch <- Map(ts_pick, dats_ch, "seas_adj")
    dats_ch <- Map(function(d, n) {d$id <- n; d}, dats_ch, basename(names(dats_ch)))

    pc_at <- list(ts_pick(ts_prcomp(do.call(rbind, dats_at)), "PC1"))
    pc_ch <- list(ts_pick(ts_prcomp(do.call(rbind, dats_ch)), "PC1"))

Then - compare the raw and PC dynamics:

    plot_series <- function(ts) {
      plot(ts$time, ts$value, type="l")
      title(ts$id[1])
    }
    
    par(mar=c(2,2,2,2), oma=c(0,0,2,0))
    layout(matrix(1:10, ncol=2))
    Map(plot_series, c(dats_at, pc_at, dats_ch, pc_ch))
    
    mtext("comparison between AT (left) and CH (right)", 3, outer=TRUE, col="red")
    
And here is the result:

<img width="862" alt="Screenshot 2020-08-19 at 8 57 31 PM" src="https://user-images.githubusercontent.com/7273684/90672610-0c0a6600-e25f-11ea-81e5-9480b13c00d4.png">

As seen from the picture - the actual trends are very similar, but PC1 is opposite.

If this is indeed the issue then half of series in production MIGHT have the wrong sign.

**Comment by christophsax** [comment]
Fantastic comparison, thanks!

Searches for 'arbeitslos' in Austria seem very whitenoise-ish until recently. If we drop them, do we get the expected result?

@ronaldindergand looked into Austrian 'DESI' at some point. Perhaps he has some ideas?
