### ISSUE TITLE
Download long-term consistent daily series

### ISSUE THREAD

**Issue by christophsax** [trendecon/trendecon#57]
In order to quickly generate a consistent long-term daily time series, it would be useful to have a single function that downloads the daily, the weekly and the monthly time series multiple times and bends them together. The same as we do for the trendecon indices, but with less infrastructure.

Something like:

```r
ts_gtrends("Wirtschaftskrise", all_frequencies = TRUE, geo = "CH")
```

This would download the daily, weekly and monthly series multiple times, bend the daily to weekly and then to monthly and return a series that is almost identical to:

```r
read_csv("https://raw.githubusercontent.com/trendecon/data/master/raw/ch/Wirtschaftskrise_mwd.csv")
````

Potential issues:

### Naming

Should we use the same function with an argument, such as `all_frequencies = TRUE`, or start from scratch, with a new function name? No strong opinion.

### Caching

This needs around 50 queries to Google, so we may want to store the series somewhere. 
`file.path(tempdir(), "gtrends")` would be an obvious default, which may be overridable with an option?

### Length

The `time` argument uses the Google time specification. With `all_frequencies = TRUE`, we may want to ignore it. Perhaps somehting like `all_frequencies_start`?

@karoliskoncevicius, could you imagine this to work? If so, could you try to implement it? I think this should have a higher priority than the hourly downloads we talked about
earlier.

**Comment by karoliskoncevicius** [comment]
@christophsax

If I understood this one right - we need to have a function that does `proc_keyword_init()` + `proc_combine_freq()`.

In order not to have daily, weekly, and monthly download code duplicated two times across the functions I think it's best to abstract that in a separate function, then call it from both `proc_keyword_init()` and `ts_gtrends()`. That function should take directory for cache as an argument, so if we set it to `tmp()` the daily and weekly and monthly data will be written there, and when we need it saved we can change that to `raw/ch` or anything really.

At least that's my initial impression.

Also - is there a reason for `proc_keyword_init()` to not do bending and seasonal adjustment?

**Comment by karoliskoncevicius** [comment]
Regarding integration of hourly data - I looked at that issue a few times, but got stock at the very beginning - google trends seems to return relative data. So if we get data for last 5 days, the biggest value will always be "100".

So if I look at the same period (5 last days) using hourly data and using daily data - I see that average are very different. So not sure how to combine.

**Comment by karoliskoncevicius** [comment]
@christophsax 

Additional idea: the functions that download the data shouldn't store them, they should just return a prepared tibble. Saving the data to the needed places will then be done by the wrappers called by the user.

**Comment by karoliskoncevicius** [comment]
@christophsax I added a prototype function for this here: https://github.com/trendecon/trendecon/blob/master/R/ts_gtrends_mwd.R

This is not a final version, but just to check if it does what you expect it to do?

Overall, it currently seems a bit hard to re-use existing functions, since they all want to write the downloaded data to local folders under certain locations. Do you think there is a need to restructure them in order to make the core functionality more reusable?

**Comment by christophsax** [comment]
Thanks, Karolis! I think your function works reasonably well. As a minimal solution, we probably could add it like that.

Alternatively, we also could use the file based functions:

We could set up the paths in a location that we retrieve via `get_trendecon_path()` (Which probably uses `getOption("trendecon_path")` or defaults to `file.path(tempdir(), "trendecon")`. A user could change the default via `set_trendecon_path()` (which sets `options()`).

In the end, we extract our series and clean up)

This could be beneficial if google blocks you in a run, and you could try to continue where you were left. Side-effect would be that you can use the existing file based functions. I think these are good enough, and don't need restructuring.

I don't have a strong opinion. What is yours?

**Comment by christophsax** [comment]
The ideal solution would be the opposite: The file writing functions should call the pure R functions. But it is too much work to change it, sow we keep it as it is for now.
