### ISSUE TITLE
Download hourly data for the last 3 days

### ISSUE THREAD

**Issue by karoliskoncevicius** [trendecon/trendecon#58]
@christophsax I am starting this issue here, instead of gtrendecon.

My current problem is this:

- past 7 day trends:

![Screenshot 2020-12-04 at 7 26 34 PM](https://user-images.githubusercontent.com/7273684/101195160-af915200-3667-11eb-81b9-5ce9c6650dcb.png)

- past month trends: 

![Screenshot 2020-12-04 at 7 27 05 PM](https://user-images.githubusercontent.com/7273684/101195170-b324d900-3667-11eb-9dc4-f022ce259e8b.png)

For example Nov 30 would be around ~25 (average) in the hourly data, but is at ~77 in the daily data.

It seems like I would get quite different values depending on how the data is sourced: last week (hourly) or last month (daily), because google trends always up-scales the maximum value to be 100, and the lowest value to be 0.

**Comment by christophsax** [comment]
I don't think this too different from the other frequencies. Getting multiple draws and averaging may help. And we will not use the hourly data in the long run. TBD.

**Comment by karoliskoncevicius** [comment]
@christophsax 

Added a first attempt at addressing this issue.

First, a few points:

1. gtrends only downloads hourly data with the format `now 7-d`, if we provide a date range instead `2021-01-22 2021-01-28` - daily data is returned for days up to 01-25. So I could not use `ts_gtrends_window()` function, but instead called `ts_gtrends()` directly.

2. hourly data is stored in a separate file with "_h" suffix. The file is not aggregated with others and is re-written on every update.

3. hourly data is integrated with the daily data by first making sure that for the overlapping days the mean values of hourly and daily data are the same. This is done by adjusting the hourly data mean to match the daily data mean. Then the missing days for the daily data are added from the hourly set. Days that have values in both hourly and daily are unchanged. This is to make sure that the values for days more than 3 days ago are fixed and not changing from every update. Only the values of last 3 days will change.

Here are the relevant commits:
https://github.com/trendecon/trendecon/commit/594261e990114e1767321119f62b496b11df91ea
https://github.com/trendecon/trendecon/commit/48d67801e2dc3ee21bf2966d489d522a196b512f

Let me know if you think this is good enough and we can test to see how it is working in production.

**Comment by christophsax** [comment]
This really seems to work! We have now data until yesterday on trendecon.org. Thanks!

@karoliskoncevicius can you close if you think that is good?
