### ISSUE TITLE
Keywords with slashes

### ISSUE THREAD

**Issue by ankargren** [trendecon/trendecon#63]
A point made by the [OECD Weekly Tracker](http://www.oecd.org/economy/weekly-tracker-of-gdp-growth/) is that it can often be useful to work with *topics* and not raw search terms. In `gtrendsR`, search interest by topic can be retrieved using Google's topic codes ([see here](https://github.com/PMassicotte/gtrendsR/issues/321)). For example, `ts_gtrends("/m/07s_c", geo = "CH")` returns search interest for the topic unemployment and is language agnostic.

 The problem is that `proc_keyword_init("/m/07s_c", "CH")` puts the files into `raw/m/07s_c`. A relatively simple fix seems to be to:

- Change e.g. line 52 in `proc_keyword_init.R` 
```
if (indicator_raw) write_csv(d, path_draws(tolower(geo), paste0(keyword, "_d.csv")))
```
to a function call, e.g. `write_raw_keyword()` analogously to `write_keyword()` that internally calls `path_keyword()`
- Change `paste0(keyword, "_", suffix, ".csv")` in `path_keyword()` to something that takes care of slashes in `keyword`.

If this is something you think would be a suitable change to your package, I am willing to make these changes and submit a pull request.

Thanks for your great work!

**Comment by christophsax** [comment]
Thanks @ankargren! Makes sense to me, and would be good to have this in the package. A pull request would be great.

@karoliskoncevicius, could you review and make sure it does not break anything else? Thanks!

**Comment by karoliskoncevicius** [comment]
Hello @ankargren ,

This would certainly be nice to have, but at the moment the issue with filenames would make it complex. We would have to somehow encode: 1) keyword, 2) geo, 3) category, 4) escape slashes within the file name and this would most likely be a breaking change for `proc_keyword_init()` and `proc_keyword()`.

So the decision is to leave it be from now and only reconsider it if real-world requests from the users will start coming in.

In the meantime we added a new function `ts_gtrends_mwd()` which prepares data in the similar way `proc_keyword_init()` pipeline would and returns the object without writing the file name. It accepts both slashes and categories.
