### ISSUE TITLE
Error in tempdisagg::td(w ~ d, method = "fast", conversion = "mean") : right hand side contains NAs

### ISSUE THREAD

**Issue by FelixZangerl** [trendecon/trendecon#66]
Hi. Thank you for making your work public!

I tried to recreate your PES indicator, according to your vignettes and when calling `proc_index` I stumbled upon the following error `Error in tempdisagg::td(w ~ d, method = "fast", conversion = "mean") : 
  right hand side contains NAs`. Do you happen to know the source of this error? I also recognized that during the `proc_keyword_init` call I got a few messages saying `no results for some ids: wirtschaftskrise`. I then tried it with different keywords but got the same error again. I checked every dataset for NAs, but couldn't find any.

Any idea what causes the issue?

**Comment by johannes97s** [comment]
Hey, i have the same Problem with tempdisagg::td(mm ~ wd, method = "fast", conversion = "mean") when calling ts_gtrends_mwd.
I found the following: 
In the Code of td: line 387 ff.
X.dtss <- lapply(X.objects, function(e) tsbox::ts_regular(tsbox::ts_default(tsbox::ts_dts(e)))
The function ts_regular takes a time Series with, lets say weekly rows and spreads it to a daily series with NAs at the missing days. I've tried to fix it with replacing the NAs with the value of the first day of the week. But that leads to a series with just weekly values up to 2011....

**Comment by karoliskoncevicius** [comment]
Seems like this is the same issue as #62

**Comment by karoliskoncevicius** [comment]
@FelixZangerl @johannes97s , thank you for reporting the issue. This is now fixed as a side effect of fixing #62 . The original issue was in `proc_keyword_init` and in `ts_gtrends_mwd` - you can read more about it at #62 .

**Comment by karoliskoncevicius** [comment]
Also a note: even thou the error is reported by `proc_keyword` - the issue is with `proc_keyword_init` as it produced data with missing days. So, after updating the pacakge, anyone experiencing this error should rerun `proc_keywrod_init`.
