### ISSUE TITLE
Default geographic region ts_gtrends

### ISSUE THREAD

**Issue by ninamuehlebach** [trendecon/trendecon#7]
Currently the default geographic region is Switzerland. Do we want to change this to “” for global queries (geo = "")?

**Comment by ninamuehlebach** [comment]
(is it the idea to post such questions/suggestions here or better in gtrendecon?)

**Comment by christophsax** [comment]
It's good here. 

`geo = ""` would be nicer, but we may break some of our scripts in `grtrendecon`.

And we need to make sure our `proc_` functions still work. So we should tackle #8 first.

**Comment by uwethuemmel** [comment]
For now, I have addressed #8 in #27 (passing `geo` through `proc_` functions) by keeping with the default "CH" - eventually, we could remove the defaults and only pass in `geo` at the top-most level.

**Comment by christophsax** [comment]
Perhaps we leave `geo = "CH"` for now. Once it becomes more universally used, we can always change.
