### ISSUE TITLE
Subsetting to a specific temporal window

### ISSUE THREAD

**Issue by JacopoCerri** [trendecon/trendecon#75]
Dear all,

I am a postdoc from the University of Sassari (Italy). Currently, I am trying to use the package that you developed, "trendecon" (https://github.com/trendecon/trendecon), to adjust GoogleTrend data by reducing sampling-related variability.
However, I noticed that functions from the package do not have any built-in command to restrict data extraction to a specific temporal window. Whenever I downloaded GoogleTrends time series, I obtained data from 2006 onwards. I am not interested in such of a long time-series, mostly because many of my queries have been searched since 2010-2011. Is there a way to restrict the extraction of robust GoogleTrends time series to a certain timespan? This is allowed, for example, by the "gtrendsR" package.

Yours sincerely,

Jacopo Cerri

**Comment by karoliskoncevicius** [comment]
Hello @JacopoCerri - thank you for reaching out,

The functionality you are interested in is now implemented in one of the development branches. On the condition that it will be approved internally it should reach the master branch soon. If you want to test it out and use it now, feel free to install `trendecon` from https://github.com/trendecon/trendecon/tree/ts_gtrends_mwd_gets_from

**Comment by karoliskoncevicius** [comment]
@JacopoCerri the `from=` argument is now in the master branch, just update the trendecon package and you should have the desired functionality available. If you have any further comments or problems please reopen this issue, or create a new one as you think appropriate. Have a nice weekend!

**Comment by JacopoCerri** [comment]
Thanks !
