### ISSUE TITLE
Error: cannot parse the supplied time format.

### ISSUE THREAD

**Issue by Crypto-nomics** [trendecon/trendecon#76]
Hi there, thank you so much for your hard work in developing this R package. I have been playing around with different functions within the package but somehow the "proc_keyword_init" function never worked for me even when I was using the example here: https://trendecon.github.io/trendecon/articles/daily-series.html

I am trying to research certain keywords from 2013 to 2020 at a global level, but tt always returns this error:

Error in `mutate()`:
! Problem while computing `trend_data = list(...)`.
ℹ The error occurred in row 220.
Caused by error:
! Cannot parse the supplied time format.
Run `rlang::last_error()` to see where the error occurred.

I traced back to the "ts_gtrends_windows" function and I guess something went wrong with the ungroup() function and maybe it's due to sys.date()..? Please let me know if I am doing anything wrong. Thank you so much!

`> proc_keyword_init(keyword = c("Climate change"), geo = "", from = "2013-01-01")
Downloading keyword: Climate change
Downloading daily data
Downloading data for 2013-01-01 2013-07-01
...
Downloading data for 2021-12-30 2022-06-27
Error in `mutate()`:
! Problem while computing `trend_data = list(...)`.
ℹ The error occurred in row 220.
Caused by error:
! Cannot parse the supplied time format.
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/dplyr:::mutate_error>
Error in `mutate()`:
! Problem while computing `trend_data = list(...)`.
ℹ The error occurred in row 220.
Caused by error:
! Cannot parse the supplied time format.
---
Backtrace:
  1. trendecon::proc_keyword_init(...)
 11. trendecon::ts_gtrends(...)
 13. base::lapply(...)
 14. trendecon FUN(X[[i]], ...)
 15. trendecon:::gtrends_with_backoff(...)
 16. base::tryCatch(...)
 17. base tryCatchList(expr, classes, parentenv, handlers)
 18. base tryCatchOne(expr, names, parentenv, handlers[[1L]])
 19. value[[3L]](cond)
 20. base::stop(e)
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/dplyr:::mutate_error>
Error in `mutate()`:
! Problem while computing `trend_data = list(...)`.
ℹ The error occurred in row 220.
Caused by error:
! Cannot parse the supplied time format.
---
Backtrace:
     ▆
  1. ├─trendecon::proc_keyword_init(...)
  2. │ └─trendecon:::ts_gtrends_windows(...)
  3. │   └─... %>% ungroup()
  4. ├─dplyr::ungroup(.)
  5. ├─tidyr::unnest(., cols = trend_data)
  6. ├─dplyr::mutate(...)
  7. ├─dplyr:::mutate.data.frame(...)
  8. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), caller_env = caller_env())
  9. │   ├─base::withCallingHandlers(...)
 10. │   └─mask$eval_all_mutate(quo)
 11. ├─trendecon::ts_gtrends(...)
 12. │ ├─stats::setNames(...)
 13. │ └─base::lapply(...)
 14. │   └─trendecon FUN(X[[i]], ...)
 15. │     └─trendecon:::gtrends_with_backoff(...)
 16. │       └─base::tryCatch(...)
 17. │         └─base tryCatchList(expr, classes, parentenv, handlers)
 18. │           └─base tryCatchOne(expr, names, parentenv, handlers[[1L]])
 19. │             └─value[[3L]](cond)
 20. │               └─base::stop(e)
 21. └─dplyr `<fn>`(`<smplErrr>`)
 22.   └─rlang::abort(...)`

**Comment by karoliskoncevicius** [comment]
Hello @Crypto-nomics , and thank you for reaching out,

Unfortunately I cannot replicate the error on my end, can you give more details about it?

1) When does the error occur - is it during the downloads, or after all the downloading is finished?
2) Which version of R are you using?
3) Are the packages up to date?

My suggestions to try first would be:

1. Install newer version of R, specially if you are under version 4.1.
2. Update all the packages, maybe by running `update.packages(ask=FALSE)` and make sure all are updated successfully without errors.

Finally, if I got your use case right, you are only interested in time-series between 2013 and 2020 - meaning that you will not be updating those series once you get them. For this you can use another function in trendecon: `ts_gtrends_mwd()`. Can you check if that one is also not working for you?

**Comment by karoliskoncevicius** [comment]
Hello, I am closing the issue now, but if this persists after updating R and the package versions - please reopen.
