### ISSUE TITLE
Oh noes, they don't like us anymore...

### ISSUE THREAD

**Issue by jyotishkarc** [trendecon/trendecon#79]
This morning, I was working with the `trendecon` package in R quite well. However, since past few hours, it is showing the "Oh noes, they don't like us anymore..." message again and again. The code chunk that I am trying to run is the following:

```
data.gtrends <- ts_gtrends(keyword = c("russia ukraine war","russia",
                                       "ukraine","russia ukraine conflict"),
                           geo = "",
                           time = "2020-06-01 2022-06-13")
```
The error that it is showing is the following:
```
Downloading data for 2020-06-01 2022-06-13
Downloading data for 2020-06-01 2022-06-13
Oh noes, they don't like us anymore...
Waiting for 5 seconds
Retrying...
Attempt 2/5
Nope, still nothing...
Waiting for 10 seconds
Retrying...
Attempt 3/5
Nope, still nothing...
Waiting for 15 seconds
Retrying...
Attempt 4/5
Nope, still nothing...
Waiting for 20 seconds
Retrying...
Attempt 5/5
Nope, still nothing...
Waiting for 25 seconds
Retrying...
Error in gtrends_with_backoff(keyword, geo, time, gprop, category, hl,  : 
  Retries exhausted!
```
I tried the same thing from my colleague's computer, and the problem was still there. I feel there's some problem on the server side. Can anyone please look into it? Thank you.

**Comment by karoliskoncevicius** [comment]
Hello @jyotishkarc 

This is completely expected - google does not allow to scrape their data endlessly and they start limiting queries based (I think) on the IP address once the number of queries exceed a certain threshold. There are only two solutions as far as I know:

1. Wait and repeat the call another day.
2. Repeat the function call from another IP address.

The fact that your colleague's computer also had the same error makes me think you share the same external IP address.

**Comment by jyotishkarc** [comment]
Thanks for clarifying. Didn't know about this. :)
