### ISSUE TITLE
Error in `mutate()` in the function ts_gtrends_mwd

### ISSUE THREAD

**Issue by jyotishkarc** [trendecon/trendecon#81]
I was trying to use the `ts_gtrends_mwd` function from the `trendecon` package in order to construct a combined daily time series of search volumes for the keywords 'russia ukraine war' and 'russia and ukraine war' for the whole world, as mentioned below:

```{r}
library(trendecon)
library(reshape2)
library(dplyr)

data_consistent <- ts_gtrends_mwd(c("'russia ukraine war' + 'russia and ukraine war'"),
                                                          from = "2019-06-01",
                                                          geo = "")
```

However, after some 'Downloading data for ...' messages on the console, I got the following error message:
```
Downloading data for 2019-06-01 2019-12-01
Downloading data for 2019-06-16 2019-12-16
Downloading data for 2019-07-01 2020-01-01
Downloading data for 2019-07-16 2020-01-16
.
.
.

Downloading data for 2021-05-06 2021-11-06
Downloading data for 2021-05-21 2021-11-21
Downloading data for 2021-06-05 2021-12-05
Downloading data for 2021-06-20 2021-12-20

Error in `mutate()`:
! Problem while computing `trend_data = list(...)`.
ℹ The error occurred in row 51.
Caused by error in `interest_over_time()`:
! Status code was not 200. Returned status code:500
Run `rlang::last_error()` to see where the error occurred.
```

Can anyone please help me fix this issue? Thank you.

**Comment by karoliskoncevicius** [comment]
Hello, thank you for reporting this.

For me this worked without errors... But I have a few ideas.

1. Try to update everything to the newest version (this includes the R itself, the trendecon package, and all of it's dependencies). A useful command `update.packages(ask = FALSE)`

2. However, based where the error occurred I suspect that google returned something that we were not anticipating. Maybe an empty result, maybe a table with fewer/more columns. I will leave this open and see if I can catch this myslef.

On your side - maybe you can try rerunning the same query again and see if you get the same error? If yes - does the error always occur on a specific date, i.e. 2021-06-20 ?

**Comment by jyotishkarc** [comment]
Thanks for your response. I was already using the latest versions of R and RStudio. Nevertheless, I saw that four packages (including `Rcpp`, `tibble` etc.) needed updates, and I updated those. I changed the date to `2020-06-02` (just a random date), and added a few more keywords. Surprisingly enough, it is working now!

However, it would be good if you can still check if that `mutate()` error occurs due to some other reason (e.g. point #2 as you mentioned above), and fix that if possible. Thank you.

**Comment by karoliskoncevicius** [comment]
@jyotishkarc I finally managed to track this issue, pull request is awaiting approval, once it passes the downloading should become robust against the reported error (500) as well as additional response (429, which I managed to get as well).

**Comment by karoliskoncevicius** [comment]
@jyotishkarc the fix is now merged into master, thanks for reporting!
