### ISSUE TITLE
Downloading on an hourly or minute basis

### ISSUE THREAD

**Issue by ninamuehlebach** [trendecon/trendecon#9]
Downloading data on an hourly or minute basis throws an error because the time stamp is not saved in the time column

Example:
`ts_gtrends(keyword = "cinema",geo = "CH",time = "now 7-d")`

Error: 
> Error in ts_boxable(x) : duplicated series: 

We can also just remove this option, i.e., not allow for hourly/minutely date.

**Comment by christophsax** [comment]
works now:

``` r
library(trendecon)
ts_gtrends(keyword = "cinema",geo = "CH",time = "now 7-d")
#> Downloading data for now 7-d
#> # A tibble: 168 x 2
#>    time                value
#>    <dttm>              <int>
#>  1 2020-05-14 14:00:00    40
#>  2 2020-05-14 15:00:00    45
#>  3 2020-05-14 16:00:00    65
#>  4 2020-05-14 17:00:00    47
#>  5 2020-05-14 18:00:00    56
#>  6 2020-05-14 19:00:00    49
#>  7 2020-05-14 20:00:00    50
#>  8 2020-05-14 21:00:00    65
#>  9 2020-05-14 22:00:00    50
#> 10 2020-05-14 23:00:00    71
#> # … with 158 more rows
```

<sup>Created on 2020-05-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
